### PR TITLE
Add shorter URL with env variables

### PR DESCRIPTION
**Pull request by mastix**
I needed a way to use shorter URLs for my podcast server.

Currently it would look like this:

podcast.myowndomain.com/projectId/datasource/slug/rss

I'd like to pass the data from the path as env variable to the server, so my .env contains the projectID, the datasource and the slug name.

So now I can use the following URL (and the mandatory information is being picked up from the env variables):

podcast.myowndomain.com/rss

I think this is a cool feature.

Sascha

### CODE REVIEW

**Comment by mastix** [comment]
@kmelve , I've also wrapped your server into a Docker Image, which has now be published to the Docker Hub. This container now runs on my server, therefore it would be great if you could merge my pull requests. :)

See: https://github.com/mastix/sanity-podcast-server-docker

**Comment by mastix** [comment]
@kmelve, are you considering to pull my requests? Otherwise I would keep and develop my fork separated from yours. Please let me know asap! 👍

**Comment by kmelve** [comment]
Thanks for the contribution @mastix, and sorry for the wait!

**Comment by mastix** [comment]
@kmelve No problem! It's just like when project don't want my contributions then I'll usually start to work on my own fork.

**Pull request merged**
